"""
Created on Fri Oct  7 13:00:27 2022

@author: David Tibbits

Columbia University, Rutgers University, Maine Gem and Mineral Museum

The purpose of this script is to quickly process variances and averages of uncalibrated
Laser Induced Breakdown Spectra (LIBS) handheld data.
The data which I primarily used was output by SciApps' program Profile Builder 
and was generated by SciApps' Z-300 Handheld LIBS. Since the data is uncalibrated,
it can not really be used to generate scientific conclusions, however
measuring the precision of the data as it relates to variance between tests on the same sample
can be used to indicate whether or not the uncalibrated data is clean enough to justify
the investments needed to generate proper calibrated data.

I now unveil to you, my LIBS-inator:
"""

